import { Bookmark, Check, Droplets, Wind, Sunrise, Sunset, RefreshCw, Clock3 } from 'lucide-react';
import WeatherIcon from './WeatherIcon';
import { formatTemperature, formatWind, formatTime, formatTimestamp, dayLabel, weatherDescription, isStale } from '../lib/weather';
export default function Forecast({ city, state, unit, saved, onSave, onRefresh, online, demo, now }) {
 const data = state.data;
 const stale = data && isStale(data, now);
 const lows = data?.daily.temperature_2m_min.filter(Number.isFinite) ?? [];
 const highs = data?.daily.temperature_2m_max.filter(Number.isFinite) ?? [];
 const min = Math.min(...lows);
 const range = Math.max(1, Math.max(...highs) - min);
 const hourIndexes = data ? data.hourly.time.map((time, index) => ({ time, index })).filter(hour => hour.time >= (demo ? data.current.time : Math.floor(now / 3600000) * 3600)).slice(0, 12) : [];
 return <section className="forecast" aria-label={`Forecast for ${city.name}`} aria-busy={state.loading}>
  <div className="place-heading"><div><p className="eyebrow">YOUR FORECAST</p><h1>{city.name}</h1><p className="muted">{[city.admin1 !== city.name ? city.admin1 : '', city.country].filter(Boolean).join(', ')}</p></div><button className={`button secondary save ${saved ? 'saved' : ''}`} onClick={onSave} aria-label={`${saved ? 'Unsave' : 'Save'} ${city.name}`}>{saved ? <Check size={17}/> : <Bookmark size={17}/>} {saved ? 'Saved' : 'Save place'}</button></div>
  {state.loading && <p role="status" className="notice loading"><RefreshCw size={16} className="spin"/> {data ? 'Updating your saved forecast…' : `Getting weather for ${city.name}…`}</p>}
  {state.error && <div className="notice error" role="alert"><span>{state.error}</span><button onClick={onRefresh} className="text-button" disabled={!online && !demo}>Try again</button></div>}
  {data && <>
   <div className="freshness"><span className={`status-dot ${stale || state.source === 'cache' || !online ? 'old' : ''}`}/><span>{demo ? 'Sample data · synthetic weather' : stale ? 'Saved forecast · may be outdated' : state.source === 'cache' || !online ? 'Saved forecast' : 'Updated from Open-Meteo'}{!demo && ` · retrieved ${formatTimestamp(data.receivedAt / 1000, data.timezone)}`}</span><button className="text-button" onClick={onRefresh} disabled={state.loading || (!online && !demo)} aria-label="Refresh forecast"><RefreshCw size={14}/> Refresh</button></div>
   <div className="current-card">
    <div className="current-main"><p className="eyebrow">{demo ? 'SAMPLE CONDITIONS' : stale ? 'SAVED CONDITIONS' : 'CURRENT CONDITIONS'}</p><div className="temperature-row"><strong className="current-temperature" data-testid="current-temperature">{formatTemperature(data.current.temperature_2m, unit)}<span>{unit === 'fahrenheit' ? 'F' : 'C'}</span></strong><div className="sky-art"><WeatherIcon code={data.current.weather_code} night={data.current.is_day === 0} size={110}/></div></div><h2>{weatherDescription(data.current.weather_code)}</h2><p className="feels">Feels like {formatTemperature(data.current.apparent_temperature, unit)} · High {formatTemperature(data.daily.temperature_2m_max[0], unit)} · Low {formatTemperature(data.daily.temperature_2m_min[0], unit)}</p><p className="model-time"><Clock3 size={13}/>{demo ? 'Illustrative conditions' : 'Modeled conditions'} · {formatTimestamp(data.current.time, data.timezone)}</p></div>
    <div className="weather-details"><div><Wind/><span>Wind</span><strong>{formatWind(data.current.wind_speed_10m, unit)}</strong></div><div><Droplets/><span>Humidity</span><strong>{data.current.relative_humidity_2m == null ? '—' : `${Math.round(data.current.relative_humidity_2m)}%`}</strong></div><div><Sunrise/><span>Sunrise</span><strong>{formatTime(data.daily.sunrise[0], data.timezone)}</strong></div><div><Sunset/><span>Sunset</span><strong>{formatTime(data.daily.sunset[0], data.timezone)}</strong></div></div>
   </div>
   <section className="panel hourly-panel" aria-labelledby="hourly-title"><div className="section-title"><h2 id="hourly-title">The next hours</h2><span>{data.timezone}</span></div>{hourIndexes.length ? <div className="hourly-scroll" tabIndex="0" aria-label="Hourly forecast; scroll for more hours">{hourIndexes.map(({ time, index }) => <div className="hour" key={time}><span>{formatTime(time, data.timezone)}</span><WeatherIcon code={data.hourly.weather_code[index]}/><span className="sr-only">{weatherDescription(data.hourly.weather_code[index])}</span><strong>{formatTemperature(data.hourly.temperature_2m[index], unit)}</strong><small><Droplets size={12}/>{data.hourly.precipitation_probability[index] == null ? '—' : `${data.hourly.precipitation_probability[index]}%`}</small></div>)}</div> : <p className="muted">Saved hourly data has ended. Refresh when you’re online.</p>}</section>
   <section className="panel daily-panel" aria-labelledby="daily-title"><div className="section-title"><h2 id="daily-title">{stale && !demo ? 'Saved 7-day forecast' : 'Next 7 days'}</h2><span>Daily forecast</span></div><div className="daily-list">{data.daily.time.slice(0, 7).map((time, index) => <div className="day" key={time}><strong>{dayLabel(time, data.utc_offset_seconds)}</strong><div className="daily-description"><WeatherIcon code={data.daily.weather_code[index]} size={27}/><span>{weatherDescription(data.daily.weather_code[index])}</span></div><span className="rain-chance" aria-label={`Chance of precipitation ${data.daily.precipitation_probability_max[index] ?? 'unavailable'} percent`}><Droplets size={14}/>{data.daily.precipitation_probability_max[index] == null ? '—' : `${data.daily.precipitation_probability_max[index]}%`}</span><div className="high-low"><span>{formatTemperature(data.daily.temperature_2m_min[index], unit)}</span><div className="temperature-track" aria-hidden="true"><i style={{ width: `${data.daily.temperature_2m_max[index] == null || data.daily.temperature_2m_min[index] == null ? 0 : (data.daily.temperature_2m_max[index] - data.daily.temperature_2m_min[index]) / range * 100}%`, marginLeft: `${data.daily.temperature_2m_min[index] == null ? 0 : (data.daily.temperature_2m_min[index] - min) / range * 100}%` }}/></div><strong>{formatTemperature(data.daily.temperature_2m_max[index], unit)}</strong></div></div>)}</div><p className="fine-print">Daily dates follow the provider’s forecast calendar. Times are local to this city.</p></section>
  </>}
 </section>;
}
