import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import App from './App.jsx';
import { berlin, tokyo, fixture } from '../tests/fixtures';
import { PREFERENCES_KEY, writeCache } from './lib/storage';
const response=data=>({ok:true,json:async()=>data});
const deferred=()=>{let resolve; const promise=new Promise(r=>{resolve=r});return{promise,resolve}};
beforeEach(()=>{localStorage.clear();window.location.hash='';vi.stubGlobal('fetch',vi.fn(async url=>String(url).includes('geocoding')?response({results:[berlin,tokyo]}):response(fixture())));Object.defineProperty(navigator,'onLine',{value:true,configurable:true});});
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();});
async function chooseBerlin(){fireEvent.click(screen.getByRole('button',{name:/Explore Berlin/i}));await screen.findByRole('heading',{name:'Berlin',exact:true});await screen.findByTestId('current-temperature');}
describe('forecast and favorites journeys',()=>{
 it('starts without requesting weather or device location',()=>{render(<App/>);expect(fetch).not.toHaveBeenCalled();expect(screen.getByLabelText('Search for a city')).toBeInTheDocument();});
 it('searches, disambiguates, shows seven-day forecast and changes units without another request',async()=>{render(<App/>);fireEvent.change(screen.getByLabelText('Search for a city'),{target:{value:'Berlin'}});fireEvent.click(screen.getByRole('button',{name:'Search'}));fireEvent.click(await screen.findByRole('button',{name:/Berlin, Germany/}));await screen.findByTestId('current-temperature');expect(screen.getByRole('heading',{name:'Next 7 days'})).toBeInTheDocument();const calls=fetch.mock.calls.length;fireEvent.click(screen.getByRole('button',{name:'Fahrenheit'}));expect(screen.getByTestId('current-temperature')).toHaveTextContent('68°');expect(fetch).toHaveBeenCalledTimes(calls);});
 it('persists explicit favorites and units, navigates, removes and retains unrelated data',async()=>{localStorage.setItem('private-other-app','do not display');const {unmount}=render(<App/>);await chooseBerlin();fireEvent.click(screen.getByRole('button',{name:'Save Berlin'}));fireEvent.click(screen.getByRole('button',{name:'Fahrenheit'}));fireEvent.click(screen.getByRole('link',{name:/Saved places/}));await screen.findByRole('heading',{name:'Your saved places'});expect(screen.queryByText('do not display')).not.toBeInTheDocument();unmount();render(<App/>);expect(screen.getByRole('button',{name:'Fahrenheit'})).toHaveAttribute('aria-pressed','true');fireEvent.click(await screen.findByRole('button',{name:'Remove Berlin'}));expect(screen.getByText('Keep your places close.')).toBeInTheDocument();expect(localStorage.getItem('private-other-app')).toBe('do not display');});
 it('does not let an older forecast replace a newer selected city even when abort is ignored',async()=>{const old=deferred();fetch.mockImplementation(url=>String(url).includes('latitude=52.52')?old.promise:Promise.resolve(response({...fixture(),timezone:'Asia/Tokyo'})));render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Explore Berlin/}));fireEvent.click(screen.getByRole('button',{name:/Explore Tokyo/}));await screen.findByTestId('current-temperature');await act(async()=>old.resolve(response(fixture())));expect(screen.getByRole('heading',{name:'Tokyo',exact:true})).toBeInTheDocument();expect(screen.getByText('Asia/Tokyo')).toBeInTheDocument();});
 it('invalidates old search responses when input changes',async()=>{const request=deferred();fetch.mockReturnValue(request.promise);render(<App/>);fireEvent.change(screen.getByLabelText('Search for a city'),{target:{value:'Berlin'}});fireEvent.click(screen.getByRole('button',{name:'Search'}));fireEvent.change(screen.getByLabelText('Search for a city'),{target:{value:'Tokyo'}});await act(async()=>request.resolve(response({results:[berlin]})));expect(screen.queryByRole('button',{name:/Berlin, Germany/})).not.toBeInTheDocument();});
 it('shows a retryable provider error without fabricated forecast',async()=>{fetch.mockResolvedValue({ok:false,status:503});render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Explore Berlin/}));expect(await screen.findByRole('alert')).toHaveTextContent(/unavailable/i);expect(screen.queryByTestId('current-temperature')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Try again'})).toBeInTheDocument();fetch.mockResolvedValue(response(fixture()));fireEvent.click(screen.getByRole('button',{name:'Try again'}));await screen.findByTestId('current-temperature');});
 it('shows honest saved-data timestamps when offline and does not fetch',async()=>{writeCache(berlin,{...fixture(),receivedAt:Date.now()-3600000});Object.defineProperty(navigator,'onLine',{value:false,configurable:true});render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Explore Berlin/}));await screen.findByTestId('current-temperature');expect(screen.getByText(/Saved forecast · may be outdated/)).toBeInTheDocument();expect(screen.getByText(/You’re offline/)).toBeInTheDocument();expect(fetch).not.toHaveBeenCalled();});
 it('handles storage write failure with a visible session-only warning',async()=>{const spy=vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('quota')});render(<App/>);await chooseBerlin();fireEvent.click(screen.getByRole('button',{name:'Save Berlin'}));expect(await screen.findByText(/Changes will last only for this visit/)).toBeInTheDocument();spy.mockRestore();});
 it('skip-to-content retains the saved-places route',()=>{window.location.hash='favorites';render(<App/>);fireEvent.click(screen.getByText('Skip to content'));expect(window.location.hash).toBe('#favorites');expect(screen.getByRole('heading',{name:'Your saved places'})).toBeInTheDocument();expect(document.getElementById('main-content')).toHaveFocus();});
 it('demo mode cannot request live providers, uses synthetic cities and separate storage',async()=>{render(<App mode="demo"/>);await chooseBerlin();expect(screen.getAllByText(/Sample data/).length).toBeGreaterThan(0);expect(fetch).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Save Berlin'}));expect(localStorage.getItem(PREFERENCES_KEY)).toBeNull();fireEvent.change(screen.getByLabelText('Search for a city'),{target:{value:'Atlantis'}});fireEvent.click(screen.getByRole('button',{name:'Search'}));await waitFor(()=>expect(screen.getByText(/No sample city matches/)).toBeInTheDocument());expect(fetch).not.toHaveBeenCalled();});
});
